# Используемый язык
language: java
# Режим обычного пользователя (собирается быстрее)
sudo: false

# После успешного завершения выполнить
after_success:
- bash <(curl -s https://codecov.io/bash)

# Уведомления
notifications:
  email:
    recipients:
    - aa112233445566778899@yandex.ru
    on_success: never
    on_failure: never

# Окружающая среда
env:
  # подключение code coverage
  global:
  - CODECOV_TOKEN="9c334fff-9caa-4459-97ea-a28454168ea1"

#Использование jdk
jdk:
- openjdk11

# Использование дополнительных сервисов
services:
- postgresql

# Перед запуском выполнить
before_install:
- psql -c 'create database tracker;' -U postgres


